"use strict";

var SERVER = {
    PORT: 8000,
    JWT_SECRET_KEY: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    // TOKEN_EXPIRATION:,
}

var DATABASE = {
    USERNAME:"root",
    PASSWORD:"root",
    NAME:"Nft_Generator_Database",
    CLUSTER_LINK:"cluster0.bexq2ac",
    USER_TYPES: {
        ADMIN: 'ADMIN',
        USER: 'USER'
    }
}

const MESSAGES ={
	SUCCESS: "SUCCESS",
	FORBIDDEN:"FORBIDDEN",
	SERVER_ERROR:"SOME ERROR OCCURED ON THE SERVER",
	UNAUTHORIZED:"UNAUTHORIZED_ACCESS",
	INVALID_TOKEN:"INVALID_TOKEN",
	INVALID_PASSWORD: "INVALID_PASSWORD",
	DUPLICATE_ENTRY:"DUPLICATE_ENTRY",
	PASSWORD_CHANGED_SUCCESSFULLY:"PASSWORD_CHANGED_SUCCESSFULLY",
	PROFILE_UPDATED_SUCCESSFULLY:"PROFILE_UPDATED_SUCCESSFULLY",
    EMAIL_ALREADY_TAKEN:"EMAIL_ALREADY_TAKEN",
	USER_NOT_FOUND:"USER_NOT_FOUND",
	USER_NOT_ALLOWDED_TO_ACCESS_THIS_PAGE:"USER_NOT_ALLOWDED_TO_ACCESS_THIS_PAGE",
	USER_NOT_ALLOWDED_TO_LOGIN:"USER_NOT_ALLOWDED_TO_LOGIN",
	USER_REGISTER_SUCCESSFULLY:"USER_REGISTER_SUCCESSFULLY",
	USER_LOGIN_SUCCESSFULLY:"USER_LOGIN_SUCCESSFULLY",
	USER_BLOCKED_SUCCESSFULLY:"USER_BLOCKED_SUCCESSFULLY",
	USER_UNBLOCKED_SUCCESSFULLY:"USER_UNBLOCKED_SUCCESSFULLY",
	USER_DELETED_SUCCESSFULLY:"USER_DELETED_SUCCESSFULLY",
	USER_LOGOUT_SUCCESSFULLY:"USER_LOGOUT_SUCCESSFULLY",
	DASHBOARD_LOADED_SUCCESSFULLY:"DASHBOARD_LOADED_SUCCESSFULLY",
	COLLECTIONS_LOADED_SUCCESSFULLY:"COLLECTIONS_LOADED_SUCCESSFULLY",
	COLLECTION_ALREADY_EXIST:"COLLECTION_WITH_THIS_NAME_ALREADY_EXIST",
	COLLECTION_CREATED_SUCCESSFULLY:"COLLECTION_CREATED_SUCCESSFULLY",
	COLLECTION_DELETED_SUCCESSFULLY:"COLLECTION_DELETED_SUCCESSFULLY",
	COLLECTION_NOT_FOUND:"COLLECTION_NOT_FOUND",
	LAYER_ALREADY_EXIST:"LAYER_ALREADY_EXIST",
	LAYER_CREATED_SUCCESSFULLY:"LAYER_CREATED_SUCCESSFULLY",
	LAYERS_LOADED_SUCCESSFULLY:"LAYERS_LOADED_SUCCESSFULLY",
	LAYER_NOT_FOUND:"LAYER_NOT_FOUND",
	IMAGES_UPLOADED_SUCCESSFULLY:"IMAGES_UPLOADED_SUCCESSFULLY",
	IMAGES_LOADED_SUCCESSFULLY:"IMAGES_LOADED_SUCCESSFULLY",
	IMAGE_NOT_FOUND:"IMAGE_NOT_FOUND",
	INCORRECT_DETAILS:"INCORRECT_DETAILS"
};

const STATUS_CODES = {
	DUPLICATE:409,
	SUCCESS:200,
	CREATED:201,
	BAD_REQUEST:400,
	UNAUTHORIZED:401,
	FORBIDDEN:403,
	NOT_FOUND:404,
	UNPROCESSABLE_ENTITY:422,
	INTERNAL_SERVER_ERROR:500
};

var APP_CONSTANTS = {
    SERVER: SERVER,
    DATABASE: DATABASE,
	MESSAGES:MESSAGES,
    STATUS_CODES:STATUS_CODES
};

module.exports = APP_CONSTANTS;



